from handlers.menu import menu_router
from handlers.reg.reg_profile import reg_profile_router
from handlers.reg.reg_name import reg_name_router
from handlers.reg.reg_bdate import reg_bdate_router
from handlers.reg.reg_sex import reg_sex_router
from handlers.reg.reg_geo import reg_geo_router
from handlers.reg.reg_photos import reg_photo_router
from handlers.reg.reg_description import reg_description_router
from handlers.reg.reg_purposes import reg_purposes_router
from handlers.reg.reg_sexf import reg_sexf_router
from handlers.reg.reg_age_min import reg_age_min_router
from handlers.reg.reg_age_max import reg_age_max_router
from handlers.profile import profile_router