from keyboards.registration import reg_keys
from keyboards.reg_profiles import reg_profile_keys
from keyboards.yesno import yesno_keys
from keyboards.sex_to_f import sexf_keys
from keyboards.sex import sex_keys
from keyboards.skip import skip_keys
from keyboards.menu import menu_keys
from keyboards.profile_settings import prof_set_keys
from keyboards.yesnoback import yesnoback_keys