from vkwave.bots import Keyboard, ButtonColor

prof_set_keys = Keyboard()
prof_set_keys.add_text_button(text="Назад", payload={"command": "menu"}, color=ButtonColor.PRIMARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Имя", payload={"command": "name"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_text_button(text="Дата рождения", payload={"command": "bdate"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Пол", payload={"command": "sex"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_text_button(text="Цели", payload={"command": "purposes"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Геопозиция", payload={"command": "geo"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_text_button(text="Описание", payload={"command": "description"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Удал. фото", payload={"command": "del_photos"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_text_button(text="Доб. фото", payload={"command": "add_photos"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Изменить возраст поиска", payload={"command": "age_f"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Изменить пол поиска", payload={"command": "sex_f"}, color=ButtonColor.SECONDARY)
prof_set_keys.add_row()
prof_set_keys.add_text_button(text="Удалить профиль", payload={"command": "delete"}, color=ButtonColor.NEGATIVE)